### ISSUE TITLE
multiprocessing 

### ISSUE THREAD

**Issue by thkuo** [leoisl/make_prg#10]
Dear development team,

I got this error from `make_prg update` after the updated alignments were available: 
```
2021-11-24 12:49:25.877 | INFO     | make_prg.subcommands.update:update:131 - Write PRG file to /net/metagenomics/data/from_moni/old.tzuhao/test_pandora/results/subset_test/by_pipeline/pangenome_updated/pangenome_updated_tmp/GC00000862_2_na_aln/GC00000862_2_na_aln.prg.fa
2021-11-24 12:49:28.138 | INFO     | make_prg.subcommands.update:update:131 - Write PRG file to /net/metagenomics/data/from_moni/old.tzuhao/test_pandora/results/subset_test/by_pipeline/pangenome_updated/pangenome_updated_tmp/GC00002479_na_aln/GC00002479_na_aln.prg.fa
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "multiprocessing/pool.py", line 119, in worker
  File "multiprocessing/pool.py", line 47, in starmapstar
  File "make_prg/subcommands/update.py", line 119, in update
  File "make_prg/prg_builder.py", line 385, in batch_update
  File "make_prg/prg_builder.py", line 418, in _update_leaf
  File "make_prg/io_utils.py", line 21, in load_alignment_file
  File "Bio/AlignIO/__init__.py", line 392, in read
ValueError: No records found in handle
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "make_prg/__main__.py", line 49, in <module>
  File "make_prg/__main__.py", line 43, in main
  File "make_prg/subcommands/update.py", line 186, in run
  File "multiprocessing/pool.py", line 274, in starmap
  File "multiprocessing/pool.py", line 644, in get
ValueError: No records found in handle
[41767] Failed to execute script __main__

```

My command was 
```
/net/metagenomics/data/from_moni/old.tzuhao/test_pandora/test_make_prg/bin/make_prg update --threads 3 \
  --update_DS /net/metagenomics/data/from_moni/old.tzuhao/test_pandora/test_make_prg/results/pangenome.update_DS   \
  --denovo_paths /net/metagenomics/data/from_moni/old.tzuhao/test_pandora/results/subset_test/by_pipeline/all_denovo_paths.txt  \ 
  --output_prefix /net/metagenomics/data/from_moni/old.tzuhao/test_pandora/results/subset_test/by_pipeline/pangenome_updated/pangenome_updated 
```
, executed using Snakemake. 

Could it be some issue with the multithreading script? Otherwise, what may I need to check first? Is it likely to rerun with those updated alignments? Thank you for considering my question.

**Comment by leoisl** [comment]
Dear thkuo,

We will soon (within 2 days or early next week) have a release which solves many bugs with the `make_prg update` command. We are in the final stages of testing it. Would it be ok for you to wait for this new version? It is possible that this bug might have been solved with it.

Cheers

**Comment by thkuo** [comment]
Sure. Thank you for the prompt reply. I look forward to the new release.

________________________________

**Comment by leoisl** [comment]
Dear @thkuo ,

we found a bug that will delay the release to next week. We apologise for this delay.

Cheers

**Comment by thkuo** [comment]
Dear @leoisl ,
I hope everything went fine. May I know how I can access the fixed version?

**Comment by leoisl** [comment]
Dear @thkuo ,

We are in the process of reviewing the code for this big update in `make_prg`. We broke the review process into 6 PRs, and 2 were already reviewed. Unfortunately, most of our group will go on break from next week, so these reviews will take longer. For now, I can offer you a pre-release of this version, which is somewhat stable in the sense that tests passed, but not yet fully reviewed by other members. You can download this pre-release version as a docker container by running `docker pull leandroishilima/make_prg:1.0.0_pre_release` or as a singularity container, if you prefer or don't have enough privileges to run docker, as `singularity pull docker://leandroishilima/make_prg:1.0.0_pre_release`. Alternatively, you can also install this using `pip`: `pip install git+https://github.com/leoisl/make_prg@update_1_0_0_pre_release` (`MAFFT` needs to be installed if you want to use `make_prg update`. With the containers, this dependency is already installed). As being basically a test user, please reply here in case of any issues, be it for installing or executing. These will be solved ASAP in order to have any bugs sorted when we merge this code back to the main fork/branch. I will have limited work time from 24th December until 10th January, but will do my best to reply you as soon as possible.

Cheers

**Comment by thkuo** [comment]
Thank you for the update. While I look forward to the stable release, I'll try this method first. Have a joyful holiday!


________________________________

**Comment by leoisl** [comment]
Stable release out now: https://github.com/iqbal-lab-org/make_prg/releases/tag/0.4.0 , sorry for the delay. Closing, feel free to reopen
